name: Windows

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download SDL2
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip"
        file-name: "sdl2.tar.gz"
    - name: Extract SDL2
      run: |
           tar xzvf "sdl2.tar.gz"
           move-item "SDL2-2.0.14" "sdl2"
           del "sdl2.tar.gz"
           dir sdl2/
    - name: Clone ImGui, ImPlot and lgw
      run: |
           git clone https://github.com/ocornut/imgui
           git clone https://github.com/epezent/implot
           git clone https://github.com/Lycoder/lgw
    - name: Build
      run: |
           ./build-win.ps1 "lgw/" "implot/" "imgui/" "sdl2/"
           dir
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest"
        files: |
            LICENSE.txt
            bin/geebly.exe
            sdl2/lib/x64/SDL2.dll
